dist: trusty
sudo: false

language: node_js
node_js:
  - "7"

install:
  - npm install truffle
  - npm install ganache-cli
  - npm install web3-utils
  - npm install secp256k1

before_script:
  - ganache-cli > ganache.log &

script:
  - truffle test
